---
bibliography: bibliography.bib
---

:::{.content-hidden}
\newcommand{\ppartial}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\iset}[1]{\llbracket #1 \rrbracket}
\newcommand{\f}[1]{\underline{#1}}
\newcommand{\bx}{\mathbf{x}}
\newcommand{\bg}{\mathbf{x}}
<style>
    .side {
        color: gray;
    }
</style>
:::

A Probabilistic Inference perspective of Memory Retrieval in Modern Associative Memories

# [HAMUX](https://bhoov.com/hamux/) as probabilistic inference

> These notes record my first attempt at understanding Associative Memory (specifically, the Hierarchical Associative Memories formed by using the rules of [HAMUX](https://bhoov.com/hamux/)) through the lens of Probabilistic Graphical Models and established techniques for probabilistic inference. Many paragraphs and examples are taken verbatim from the cited sources; I found it very helpful in places to manually transcribe the original reference notes.
>
> With the exception of @coughlan2009Tutorial, which was used only to introduce factor graphs, I found the sources referenced in this work to be highly relevant to our exploration. Indeed, it seems that my instinct that AM energy minimization as probabilistic inference has relevance even to exploring codes that approach the Shannon Limit. I do not yet know much about these potential applications, but I expect this to be a continually rewarding intellectual exploration that I hope unlocks future research directions for us.
>
> Some prior works have discussed Hopfield memory retrieval from the perspective of variational infernece e.g., @mezard2017Meanfielda and @annabi2022relationship, but neither of these discuss the view of Associative Memories as operations on a general factor graph in HAMUX [@hoover2022a].

## Background
### Factor Graphs

*Overview adapted from [@coughlan2009Tutorial]*

We can express many kinds of "decomposed joint probability distributions" graphically. For example, consider the Bayesian network described by the simple equation

$$
P(w,x,y,z) = P(w)P(x)P(y|w)P(z|w,x)
$$

This can be expressed in the following diagram

:::{#lst-bayes-graph lst-cap='Example bayesian graph'}
```{mermaid}
flowchart TD
    W((w)) --> Z((z))
    W((w)) --> Y((y))
    X((x)) --> Z((z))
```
:::

Of course, this is not the only way the joint probability can be decomposed. Decomposing this joint probability is the structure of the problem and a choice of the researcher.

Instead of conditional probabilities, we can also model a joint distribution by decomposing it into pairwise, undirected potentials normalized by $Z$. This form is called the **Markov Random Field**. 

$$
P(w,x,y,z) = \frac1Z f_{wx}(w,x) f_{xz}(x,z) f_{yz}(y,z) f_{wy}(w,y).
$$

This can be expressed as an undirected graph where information is passed along nodes both ways.

```{mermaid}
flowchart LR
    W((w)) --- X((x))
    W((w)) --- Y((y))
    X((x)) --- Z((z))
    Y((y)) --- Z((z))
```

Expressing more complex factorizations, i.e., those where the factors are functions of more than two variables, is best accomplished by a form of hypergraph, where the edges become hyperedges, a special type of nodes themselves.

Consider the factorization
$$
P(w,x,y,z) = \frac1Z f(w,x,y) g(y,z) h(z).
$$

This can be drawn as the **factor graph**, where square nodes are the factors (hyperedges) that connect multiple nodes.

:::{#lst-factor-graph lst-cap='Example factor graph'}
```{mermaid}
flowchart TD
    w((w)) --- f[f]
    x((x)) --- f[f]
    y((y)) --- f[f]
    y((y)) --- g[g]
    z((z)) --- g[g]
    z((z)) --- h[h]
```
:::

We live in the realm of undirected factor graphs (@lst-factor-graph) for the remainder of these notes, but know that there are likely strong connections to the conditional, Bayesian, directed graph of @lst-bayes-graph.

## Inference in General PGMs

*Summarized/adapted from [@jordanProbabilistic]*

Now let us consider the general case of expressing joint probabilities as a graph. Let $U$ denote a set of nodes of a graph, and let $X_i$ denote the random variable associated with node $i$, for $i \in U$. Let $X_C$ denote the subset of random  variables associated with a subset of nodes $C$, for any $C \subseteq U$, and let $X = X_U$ denote the collection of random variables associated with the graph. In the current work, we consider only the family of undirected graphs, where we describe the basic subsets as "cliques" of the graph -- subsets of nodes that are *completely connected*. We can describe the potential of a given clique $C$ as $\psi_C (x_C)$, which is a general function assigning a positive real number to each configuration $x_C$;

$$
p(x) = \frac1Z \prod_{C\in \mathcal{C}} \psi_C(x_C) \prod_{i \in U} \pi_i(x_i).
$${#eq-joint-prob}

Here $\mathcal{C}$ is the set of cliques associated with the graph, $Z$ is the explicit normalizing factor ensuring that $\sum_x p(x) = 1$, and $\pi_i(x_i)$ is some prior assigned to node $i$.

**Inference**

Let $(E, F)$ be a partitioning of the node indices of a graphical model into disjoint subsets, such that $(X_E, X_F)$ is a partitioning of the random variables.

We generally care about 2 kinds of inference:

- *Marginal Probabilities*:
  
  $$
  p(x_E) = \sum_{x_F} p(x_E, x_F)
  $$

- *Maximum a Posteriori (MAP) probabilities*

  $$
  p^\star(x_E) = \max_{x_F} p(x_E, x_F)
  $$

With these basic computations, we can compute other quantities of interest e.g., the conditional probability of latent variables $F$ given evidence $E$:

$$
p(x_F | x_E) = \frac{p(x_E, x_F)}{\sum_{x_F} p(x_E, x_F)}.
$$

**QUESTIONS**

- *How do these operations relate to memory retrieval?*
- *Where do "beliefs" come into the computation? Not at all?*

### (Loopy) Belief Propagation

The goal of Belief Propagation (BP) (a.k.a., the "sum-product" algorithm) is to perform inference on our joint probability distribution. Consider the following simple joint probability:

$$
p(x) = \frac1Z \psi_{12}(x_1, x_2) \psi_{23}(x_2, x_3) \psi_{34}(x_3, x_4) \psi_{35}(x_3, x_5)
$$

```{mermaid}
flowchart TD
    x1((x1)) --- psi12[Ψ_12]
    x2((x2)) --- psi12[Ψ_12]
    x2((x2)) --- psi23[Ψ_23]
    x3((x3)) --- psi23[Ψ_23]
    x3((x3)) --- psi34[Ψ_34]
    x3((x3)) --- psi35[Ψ_35]
    x4((x4)) --- psi34[Ψ_34]
    x5((x5)) --- psi34[Ψ_35]
```

Say our goal is to perform inference to compute the marginal $p(x_5)$ (also called the "belief" of $x_5$). We assume that an oracle can tell us the optimal *elimination order* in which we compute the marginals:

$$
\begin{aligned}
p(x_5) &= \frac1Z \sum_{x_3} \psi_{35}(x_3, x_5) \sum_{x_4} \psi_{34}(x_3, x_4) \sum_{x_2} \psi_{23}(x_2, x_3) \sum_{x_1} \psi_{12}(x_1, x_2)\\
&= \frac1Z \sum_{x_3} \psi_{35}(x_3, x_5) \sum_{x_4} \psi_{34}(x_3, x_4) \sum_{x_2} \psi_{23}(x_2, x_3) m_{12}(x_2)\\
&= \frac1Z \sum_{x_3} \psi_{35}(x_3, x_5) \sum_{x_4} \psi_{34}(x_3, x_4) m_{23}(x_3)\\
&= \frac1Z \sum_{x_3} \psi_{35}(x_3, x_5) m_{34}(x_3)\\
&= \frac1Z m_{35}(x_5)\\
\end{aligned}
$$

**Note that this is a "tree-like" factor graph where the marginal can be computed exactly using a simple elimination ordering.** For arbitrary graphs, it can be NP-hard to compute the best elimination ordering.

We describe the marginal 

$$
m_{ij}(x_j) := \sum_{x_i} \psi_{ij}(x_i, x_j) \prod_{k \in N(i) \setminus j} m_{ki}(x_i)
$${#eq-msg}

to be the "message" passed from node $i$ to node $j$, where $N(i)$ is the set of neighbors of node $i$.

:::{.callout-note}
I don't love interpreting the notation $m_{ij}(x_j)$ by looking at the order of indices in the subscript to represent a message from node $i$ to node $j$. There are cases where a message is a function of more than just the variable at the receiving node. It would be better to think of a message using the defintion of @eq-msg, and know that all arguments to a message indicate a node that has not yet been summed over. For the computer scientist, we can use the convention that the first argument to the message indicates the intended "receiving node"; in the case of multiple arguments, this convention implies that our graph ordering should eliminate the first argument last.
:::

An elegant view of the elimination process described above is that of *local computation* and *message routing*, where messages arriving at leaf nodes are necessarily marginal probabilities. However, in general we can think of a "message" as an unnormalized marginal probability

$$
p(x_i) \propto \prod \prod_{k \in N(i)} m_{ki} (x_i).
$$

The above is a way that a marginal probability can be computed using BP. The same computation can be done to compute the MAP; we simply replace “sum” with “max” throughout in both cases, where the underlying justification is that "max" commutes with products just as "sum" does.

:::{.callout-note}
The reference paper makes the following note about the similarities between message passing and neural networks:

> Neural network[s] also involve message-passing algorithms and local numerical operations. An important difference, however, is that in the neural network setting each node generally has a single “activation” value that it passes to all of its neighbors. In the sum-product  algorithm, on the other hand, individual messages are prepared for each neighbor. Moreover, the message $m_{ij}(x_j)$ from $i$ to $j$ is not included in the product that node $j$ forms in computing a message to send back to node $i$. The sum-product algorithm avoids “double-counting.”

This indeed holds for traditional feed-forward networks which are not recurrent in their activations. The activations in AMs represent a form of recurrent message passing as is used in [*variational inference*](#sec-variational-inf), which will be explained later.
:::


Exact marginal computation via elimination is described excellently in [@jordanProbabilistic], wherein the exact marginal probability for any node in an *arbitrary graph* can be computed using junction trees and the perfect ordering in which to eliminate the nodes.

### Variational Inference in PGMs

Because exact inference is intractable for many factor graphs, we often prefer some approximation. @jordanProbabilistic excellently summarizes common choices for approximation e.g., Gibbs sampling and Metropolis-Hastings (forms of MCMC used often in e.g., Boltzmann machines) and importance sampling. Please refer to the reference for details on these methods.

However, @jordanProbabilistic describes one particular form of approximate inference in PGMs called "Variational Methods" that converts the problem of "probabilistic inference" into a problem of optimization. The difference between this method and importance sampling is that, instead of choosing a single *guess distribution* $q(x)$ a priori, a family of approximating distributions $\{q(x)\}$ is used instead. The optimization machinery chooses a particular member from this family.

:::{.callout-note}
@liu2019Stein have a modern technique for variation inference called "Stein Variational Gradient Descent", in which they explain variational inference as:

> Variational inference instead frames the Bayesian inference problem into a deterministic optimization that approximates the target distribution with a simpler distribution by minimizing their KL divergence
> ...
> both the accuracy and computational cost of variational inference critically depend on the set of distributions in which the approximation is defined. Simple approximation sets, such as these used in the traditional mean field methods, are too restrictive to resemble the true posterior distributions, while more advanced choices cast more difficulties on the subsequent optimization tasks
> ...

TODO FIX ME

> Variational inference approximates the target distribution p(x) using a simpler distribution q∗(x) found in a predefined set Q = {q(x)} of distributions by minimizing the KL divergence, that is,  q∗ = arg min  q∈Q  {KL(q || p) ≡ Eq[log q(x)] − Eq[log p ̄(x)] + log Z}, (4)  where we do not need to calculate the constant log Z for solving the optimization. The choice of set Q is critical and defines different types of variational inference methods. The best set Q should strike a balance between i) accuracy, broad enough to closely approximate a large class of target distributions, ii) tractability, consisting of simple distributions that are easy for inference, and iii) solvability so that the subsequent KL minimization problem can be efficiently solved.

It is my belief that Associative Memory is concerned with an expressive class of set $\mathcal{Q}_{AM}$ that easily solve the KL minimization problem.

The fundamental realization is that the $q^\star$ can be computed as 



:::

We begin by noting that the joint probability $p(x)$ can be viewed as a solution to an optimization problem. In particular, define the energy of configuration $x$ by $E(x) = - \log p(x) - \log Z$, and define the *variational free energy* as 

$$
\begin{aligned}
F({q(x)}) &= \sum_x q(x) E(x) + \sum_x q(x) \log q(x)\\
 &= -\sum_x q(x) \log p(x) + \sum_x q(x) \log q(x) - \log Z
\end{aligned}
$${#eq-var-free-energy}

@eq-var-free-energy is equal (up to an additive constant) to the KL-divergence between $q(x)$ and $p(x)$, is minimized at $q(x) = p(x)$, and attains value $-\log Z$ at the minimum.

> **Minimizing an arbitrary $F$ is as difficult as doing exact inference**, and much effort has been invested into finding approximate forms of $F$ that are easier to minimize.

:::{.callout-note}
It is my belief that the form of all Associative Memories (i.e., constraining activations $q_i(x_i)$ to be the derivative of some convex Lagrangian whose energy is described by the Legendre Transform) is one of these "approximate forms" that is much easier to minimize. I will try to defend this stance using my shaky math below.
:::

Case study: Learning Parameters via energy minimization is MLE  for a 2-layer Dense AM.

#### Example: the Mean-Field approximation

The simplest variational algorithm is the *mean field* approximation, in which $\{q(x)\}$ is restricted to the family of factorized distributions: $q(x) = \prod_i q_i(x_i)$ (i.e., a world where all variables are independent). In this case, $F$ from @eq-var-free-energy simplifies to

$$
F_{MF}(\{q(x)\}) = -\sum_C \sum_{x_C} \log \psi_C(x_C) \prod_{i \in C} q_i(x_i) 
   + \sum_i \sum_{x_i} q_i (x_i) \log q_i (x_i),
$$

subject to the constraint $\sum_{x_i} q_i(x_i) = 1$. In this particular case, we can solve for the optimal distribution $q_i^\star(x_i)$ by setting the derivative of $F_{MF}$ w.r.t. $q_i (x_i)$ equal to zero:

$$
q_i^\star (x_i) = \alpha \exp \left(\sum_C \sum_{x_C \setminus i} \log \psi_C (x_C) \prod_{j \in C, j \neq i} q_j (x_j) \right),
$${#eq-mf-inference}

where $\alpha$ is a normalization constant chosen so that $\sum_{x_i} q_i (x_i) = 1$. The sum over cliques $C$ is over all cliques that node $i$ belongs to.

@eq-mf-inference is an *approximate inference algorithm*. We initialize approximate marginals $q_i(x_i)$ for all nodes in the graph and then update the approximate marginal at one node based on those at neighboring nodes (note that RHS of @eq-mf-inference depends only on cliques that node $i$ belongs to). This yields a message passing algorithm similar to neural networks; in particular, the value $q_i(x_i)$ can be viewed as the *activation* of node $i$.

#### Example: the Bethe approximation

The mean-field energy depends only on approximate marginals at single nodes, the *Bethe free energy* depends on approximate marginals at single nodes $q_i(x_i)$ as well as approximate marginals on cliques $q_C(x_C)$. This allows for more elaborate approximations to the free energy (@eq-var-free-energy) with better approximate marginal probabilities:

$$
F_\beta (\{q_i, q_C\}) = \sum_C \sum_{x_C} q_C(x_C) \log \frac{q_C (x_C)}{\psi_C(x_C)} - \sum_i (d_i - 1) \sum_{x_i} q_i (x_i) \log q_i (x_i),
$${#eq-f-bethe}

where $d_i - 1$ is the number of cliques that node $i$ belongs to.

:::{.callout-note}
It is unclear to me which terms in @eq-f-bethe are included in the sum over the cliques? I believe there should be two distinct terms in the RHS.
:::

The approximate clique marginals and the approximate singleton marginals must satisfy a simple marginalization constraint: $\sum_{x_C \setminus i} q_C(x_C) = q_i (x_i)$. **When we add Lagrange multipliers and differentiate the Lagrangian we obtain a set of fixed point equations.** Surprisingly, these equations end up being equivalent to the "sum-product" algorithm for trees (@eq-msg). The messages $m_{ij}(x_j) are simply exponentiated Lagrange multipliers. Thus, the Bethe approximation is equivalent to applying the local message passing scheme developed for trees to graphs that have loops (see @yedidiaBethe). This approach to approximate inference algorithms has been very successful in the domain of error-control coding, allowing practical codes based on graphical models to nearly reach the Shannon Limit.

:::{.callout-note}
I believe this last statement

> ... allowing practical codes based on graphical models to nearly reach the Shannon Limit.

refers to the connection between approximate probabilistic inference using Loopy Belief Propagation and Turbocodes , see [this paper](https://arxiv.org/abs/1301.6725) written by the authors of my reference notes in collaboration with Kevin Murphy.
:::


## From PGMs to [HAMUX](https://bhoov.com/hamux/)


**Turning probabilities into energy**

Converting a joint probability (@eq-joint-prob) to a joint energy is possible through the Boltzmann distribution:

\begin{align}
p(x) &= \frac{ \exp (- E(x))}{Z} \\
\implies E(x) &= - \log p(x) - \log Z \\
&= - \sum_{C \in \mathcal{C}} \log \psi_C(x_C) - \sum_{i \in U} \log \tilde{\pi}_i(x_i) - \log Z
\end{align}

We will drop the constant shift $\log Z$ and use the energy potential $\phi_C(x_C) := -\log \psi_C(x_C)$ to denote the new "energy factors" and $\tilde{\pi}_i(x_i) := -\log \pi_i(x_i)$ to denote the "energy priors". Thus,

$$
E(x) = \sum_{C \in \mathcal{C}} \phi_C(x_C) + \sum_{i} \tilde{\pi}_i(x_i),
$${#eq-joint-energy}

which is the general form of the energy hypergraph used in **HAMUX**. We call the energy factor $\phi_C(x_C)$ an interaction or *synaptic energy* and $\tilde{\pi}_i(x_i)$ the *neuron energy*.

:::{.callout-note}
I am unsure if the specification of priors $\tilde{\pi}$ is correct to show equivalence. The above could be written only in terms of factors $\phi_C(x_C)$.
:::


## Energy Minimization of AMs is variational inference in PGMs {#sec-variational-inf}

If the neuron energies (i.e., the neg. log. of prior probilities) are defined through the Legendre Transform of a convex "Lagrangian" function, we some nice guarantees on inference by energy minimization.

# Hopfield Memory Retrieval from the perspective of Probabilistic Inference

## Background on Message Passing

> BP's Sum-product Algorithm and Max-product algorithm on factor graphs. Notes from @yedidia2005Constructing and [these lecture notes](https://github.com/krashkov/Belief-Propagation/blob/master/1-SummaryPGMandBP.ipynb).

*The sum-product algorithm (SPA) computes **marginals***

The sum-product algorithm is used to compute marginal probabilities of a node given evidence from other nodes. Here we are consider a factorization of the joint probability consisting of exclusively pairwise potentials that would allow us to show the graph as an MRF, but for completeness we choose the factor graph representation. The graph

```{mermaid}
flowchart LR
classDef factor fill:darkred,color:white,stroke-width:2px;
classDef prior fill:teal,color:black,stroke-width:2px;

x1((x1)) --- fa[Ψa]
%% x1 --- f1[ɸ1]
fa --- x4((x4))
%% x4 --- f4[ɸ4]
x2((x2)) --- fb[Ψb]
%% x2 --- f2[ɸ2]
fb --- x4
x3((x3)) --- fc[Ψc]
%% x3 --- f3[ɸ3]
fc --- x4
x4 --- fd[Ψd]
fd --- x5((x5))
%% x5 --- f5[ɸ5]
x5 --- fe[Ψe]
fe --- x6((x6))
%% x6 --- f6[ɸ6]
x5 --- ff[Ψf]
ff --- x7((x7))
%% x7 --- f7[ɸ7]

class fa factor;
class fb factor;
class fc factor;
class fd factor;
class fe factor;
class ff factor;
class f1 prior;
class f2 prior;
class f3 prior;
class f4 prior;
class f5 prior;
class f6 prior;
class f7 prior;
```

has total probability

$$
P(x_1, x_2, x_3, x_4, x_5, x_6, x_7) = Z^{-1} \psi_a(x_1,x_4) \psi_b(x_2,x_4) \psi_c(x_3,x_4)\psi_d(x_4,x_5)\psi_e(x_5,x_6)\psi_f(x_5,x_7),
$$

where $Z$ is the normalizing constant.

Arbitrary marginals can be computed by exploiting the underlying graph structure. For example, to compute the marginal for node $x_4$, we can collect summations over certain variables to only the factors that depend on that variable.

$$
\begin{aligned}
  P(x_4)&=Z^{-1}\sum_{x_1,x_2,x_3,x_5,x_6, x_7} P(x_1, x_2, x_3, x_4, x_5, x_6, x_7) = \\
  &= Z^{-1}\sum_{x_1,x_2,x_3,x_5,x_6,x_7} \psi_a(x_1,x_4)\psi_b(x_2,x_4)\psi_c(x_3,x_4)\psi_d(x_4,x_5)\psi_e(x_5,x_6)\psi_f(x_5,x_7) = \\
  &= Z^{-1}\sum_{x_1,x_2,x_3,x_5,x_6} \psi_a(x_1,x_4)\psi_b(x_2,x_4)\psi_c(x_3,x_4)\psi_d(x_4,x_5)\psi_e(x_5,x_6)
  \left[\sum_{x_7} \psi_f(x_5,x_7)\right] = \\
  &= Z^{-1}\sum_{x_1,x_2,x_3,x_5,x_6} \psi_a(x_1,x_4)\psi_b(x_2,x_4)\psi_c(x_3,x_4)\psi_d(x_4,x_5)\psi_e(x_5,x_6)
  m_{f \to 5}(x_5) = \\
  &= Z^{-1}\sum_{x_1,x_2,x_3,x_5} \psi_a(x_1,x_4)\psi_b(x_2,x_4)\psi_c(x_3,x_4)\psi_d(x_4,x_5)
  \left[\sum_{x_6} \psi_e(x_5,x_6)\right]m_{f \to 5}(x_5) = \\
  &= Z^{-1}\sum_{x_1,x_2,x_3,x_5} \psi_a(x_1,x_4)\psi_b(x_2,x_4)\psi_c(x_3,x_4)\psi_d(x_4,x_5)
  \bigg[m_{e \to 5}(x_5)m_{f \to 5}(x_5)\bigg] = \\
  &= Z^{-1}\sum_{x_1,x_2,x_3} \psi_a(x_1,x_4)\psi_b(x_2,x_4)\psi_c(x_3,x_4)
  \left[\sum_{x_5} \psi_d(x_4,x_5)n_{5 \to d}(x_5)\right] = \\
  &= Z^{-1}\sum_{x_1,x_2,x_3} \psi_a(x_1,x_4)\psi_b(x_2,x_4)\psi_c(x_3,x_4)m_{d \to 4}(x_4) = \\
  &= Z^{-1}\left[\sum_{x_1} \psi_a(x_1,x_4)\right]\left[\sum_{x_2} \psi_b(x_2,x_4)\right]\left[\sum_{x_3} \psi_c(x_3,x_4)\right]m_{d \to 4}(x_4) = \\
  &= Z^{-1}m_{a \to 4}(x_4)m_{b \to 4}(x_4)m_{c \to 4}(x_4)m_{d \to 4}(x_4)
\end{aligned}
$$

The normalization constant can be computed by summing the product of incoming messages over all possible values of $x_4$:

$$
  Z=\sum_{x_4}m_{a \to 4}(x_4)m_{b \to 4}(x_4)m_{c \to 4}(x_4)m_{d \to 4}(x_4).
$$

Definitions for the messages $m$ and $n$ are given below in @eq-message-update-rules-spa.

### General Sum-Product Algorithm (on factor graphs) {#sec-spa}

The example computation-of-the-marginal exercise above can be extended to arbitrary factor graphs in an algorithm called the **Sum-Product Algorithm** (SPA). SPA is exact when the graphs have no loops, and approximate when loops exist. Let indices $\{a, b, c, \ldots\}$ index the factor nodes $\mathcal{M}$ and $\{i, j, k, \ldots\}$ index the variable nodes $\mathcal{S}$. Additionally, each factor $\psi_a$ can take an arbitary number of variables $\geq 1$ as arguments, which we shorthand write using using the notation $\psi_a(\bx_a)$, where 

$$
\bx_a := \{x_k \mid \text{$k \in \mathcal{S}$ and variable $x_k$ is an argument to factor $a$}\}.
$$

The goal of SPA is to compute marginal probabilities

$$
% b_i(x_i) := p(x_i) = \sum_{\substack{\text{all values of $\bx_J$}\\J := S \setminus i}} p(x_i, \bx_J) \equiv \sum_{\bx_{S \setminus i}} p(x_i, \bx_{S \setminus i}).
b_i(x_i) := p(x_i) = \sum_{\bx \setminus x_i} p(\bx).
$${#eq-marginal}

These marginal probabilities are called the *beliefs*.

We need to consider two kinds of messages: messages from factors to nodes $m_{a \to i} (x_i)$ and messages from nodes to factors $n_{j \to a} (x_j)$:

$$
\begin{aligned}
n_{j \to a}^{(t+1)} (x_j) &= \prod_{b \in N(j) \setminus a} m_{b \to j}^{(t)} (x_j) \\
m_{a \to i}^{(t)} (x_i) &= \sum_{\bx_a \setminus x_i} \psi_a (\bx_a) \prod_{j \in N(a) \setminus i} n_{j \to a}^{(t)} (x_j).
\end{aligned}
$${#eq-message-update-rules-spa}

The notations are explained below, with superscript $t$ indicating one convention for the recurrent updates for these messages (see [these lecture notes](https://web.stanford.edu/~montanar/RESEARCH/BOOK/partD.pdf?fbclid=IwZXh0bgNhZW0CMTEAAR1Vn3MpmqtDHx03JQs_s4WCJEuq87pj2W3zEW2dTD0PLBanksdNQWNbwP4_aem_nKrAsIYbNkjODr0_R0fsSA) for more details):

- $\sum_{\bx_a \setminus x_i}$ indicates to sum over all possible values for all arguments of $f_a$, keeping $x_i$ fixed as given.
- $N(a) \setminus i$ denotes all variable nodes that are **neighbors** of factor $a$ except variable node $i$. Likewise, $N(j) \setminus a$ denotes all factor nodes that are **neighbors** of variable node $j$ except for factor $a$.

At any time $t$ in the BP algorithm, we can compute the *belief* $b_i^{(t)}(x_i)$ for a variable node $i$, which represents the current BP approximation to the exact marginal probability function $p_i(x_i)$. $b_i^{(t)}(x_i)$ can be computed from the equation

$$
b_i^{(t)}(x_i) \propto \prod_{a \in N(i)} m_{a \to i}^{(t)}(x_i),
$${#eq-belief}

which will need to be normalized to sum to one to be a true "belief" or marginal probability. The BP message-update equations are iterated until they (hopefully) converge, at which point the beliefs can be read off from @eq-belief.

BP can also be used to compute joint beliefs $b_S(\bx_S)$ over sets of variable nodes $S$ that may contain more than one node. Consider computing the joint belief for all nodes connected to factor $a$. Then,

$$
b_a^{(t)}(\bx_a) \propto \;\; \psi_a(\bx_a) \prod_{i \in N(a)} n_{i \to a}^{(t)}(x_i) \;\; \propto \;\; \psi_a(\bx_a) \prod_{i \in N(a)} \prod_{c \in N(i) \setminus a} m_{c \to i}^{(t)}(x_i).
$${#eq-joint-belief}

**TODO** discuss how belief would be computed on an arbitrary set of nodes surrounded by arbitrary factors?

The BP algorithm is simply a dynamic programming algorithm that organizes the computations necessary to compute marginal probability distributions in such a way that they become tractable.

:::{.callout-note}
Interestingly, we can directly derive the message update rules of @eq-message-update-rules-spa from @eq-belief and @eq-joint-belief, in addition to the marginalization condition that

$$
b_i(x_i) = \sum_{\bx_a \setminus x_i} b_a(\bx_a).
$$

Thus, we can alternatively describe BP in terms of recurrent belief update as follows. Given:

$$
\begin{aligned}
b_i(x_i) &\propto \prod_{a \in N(i)} m_{a \to i} (x_i) \\
m_{a \to i}(x_i) &= \sum_{\bx_a \setminus x_i} \psi_a(\bx_a) \prod_{j \in N(a) \setminus i} n_{j \to a}(x_j) \\
n_{j \to a}(x_j) &= \prod_{c \in N(j) \setminus a} m_{c \to j} (x_j) = \frac{b_j(x_j)}{m_{a \to j}(x_j)} \\
% b_i(x_i) &= \sum_{\bx_a \setminus x_i} \left[ \psi_a(\bx_a) \prod_{j \in N(a) \setminus i} \frac{b_j(x_j)}{m_{a \to j}(x_j)} \right],\\
\end{aligned}
$$

we can compute the iterative belief update as

$$
\begin{aligned}
b_i^{(t+1)}(x_i) &\propto \prod_{a \in N(i)} m_{a \to i}^{(t+1)} (x_i) \\
m_{a \to i}^{(t+1)}(x_i) &= \sum_{\bx_a \setminus x_i} \psi_a(\bx_a) \frac{b_j^{(t)}(x_j)}{m_{a \to j}^{(t)}(x_j)} \\
\end{aligned}
$$


<!-- $$
b_i^{(t+1)}(x_i) \propto \prod_{a \in N(i)} \sum_{\bx_a \setminus x_i} \left[ \psi_a(\bx_a) \prod_{j \in N(a) \setminus i} \frac{b_j^{(t)}(x_j)}{m_{a \to j}^{(t)}(x_j)} \right].\\
$$ -->

Unfortunately, these rules still require you to keep around auxiliary message information in the denominator, hence why the message update rules are generally preferred.
:::

## General Max-Product Algorithms (on factor graphs) {#sec-mpa}

The SPA algorithm in @sec-spa is one form of inference when the goal is to compute marginal probabilities. However, we may prefer to compute the *max-marginal* at each node, also called the maximum-a-posteriori (MAP) of an unknown quantity (where MAP can be viewed as a regularized version of maximum-likelihood estimatation (MLE)).

The max-marginal of each node is defined by 

$$
% \hat{b}_i(x_i) = \max_{\substack{\text{all values of $\bx_J$}\\J := S \setminus i}} p(x_i, \bx_J) \equiv \max_{\bx_{S \setminus i}} p(x_i, \bx_{S \setminus i}).
\hat{b}_i(x_i) = \max_{\bx \setminus x_i} p(\bx).
$${#eq-max-marginal}

If there are no "ties" at a given node, the unique global MAP assignment is

$$
x_i^\star = \mathop{\mathrm{argmax}}_{x_i} \;\hat{b}_i(x_i).
$$

Because the 'max' operation distributes the same way as the 'sum' operation, one can simply take the examples and definitions from above and replace all instances of summation with maximization.

$$
\begin{aligned}
n_{j \to a}^{(t+1)} (x_j) &= \prod_{b \in N(j) \setminus a} m_{b \to j}^{(t)} (x_j) \\
m_{a \to i}^{(t)} (x_i) &= \max_{\bx_a \setminus x_i} \psi_a (x_i, \bx_a) \prod_{j \in N(a) \setminus i} n_{j \to a}^{(t)} (x_j).
\end{aligned}
$${#eq-message-update-rules-mpa}

## From message passing to memory retrieval

Associative Memory in the language of [HAMUX](https://bhoov.com/hamux/) is also represented as a factor graph called a *Hierarchical Associative Memory* (HAM), though each HAM is defined in terms of energies and not probabilities. As above, we consider a general HAM described by a set of *variable* nodes (described by the collection of hidden variables $\bx$ and a corresponding collection of non-linear activations $\mathbf{g}$, indexed by $\mathcal{S}$), and a set of *interaction* or *factor* nodes (indexed by $\mathcal{M}$). Assume the variable nodes are split into $N$ non-overlapping regions $\mathcal{R} := \{\mathcal{R}_1, \mathcal{R}_2, \ldots, \mathcal{R}_N\}$ s.t. $\bigcup_{i=1}^N \mathcal{R}_i = \mathcal{S}$, then each set of activations $\mathbf{g}_{\mathcal{R}_i} = \f{\mathbf{g}_{\mathcal{R}_i}} \left( \bx_{\mathcal{R}_i} \right)$ is constrained such that the non-linearity $\f{\mathbf{g_{\mathcal{R}_i}}} := \partial_0 \mathcal{L}_i$ is the derivative function of some convex Lagrangian function $\mathcal{L}_i$ defined on node region $i$. Simplifying notation, let $\bx_i$ indexed starting with $i \in \{1, \ldots, N\}$ be a shorthand for $\bx_{\mathcal{R}_i}$, then each $(\bx_i, \mathbf{g}_i)$ pair are conjugate variables under the Legendre Transform of the region's Lagrangian defined as

$$
\hat{\mathcal{L}}_i(\mathbf{g}_i) = \mathbf{g}_i \cdot \bx_i - \mathcal{L}_i (\bx_i).
$${#eq-legendre-transform}

:::{.callout-note}
Whenever there is a clash of notation between the output of a function and the function itself I will use underscores to denote the function. I.e., I often want to manipulate the output $f := \f{f}(x)$ as a normal variable, but I want to refer to the original function $\f{f}$ for functional transformations e.g., the partial gradient $\partial_0 \f{f}$.

In this manner I can continue to keep all normal annotations e.g., denoting vector-valued functions in **bold**.
:::

Interaction energies $J_a(\mathbf{g}_a)$ serve as the factors, with indices starting with $a \in \mathcal{M}$, and $\mathbf{g}_a$ indicate the subset of activations in the neighborhood of factor $a$.

The total energy describing a HAM is the sum of all interaction energies, plus regularizing terms that result from the Legendre Transform of the Lagrangian on each region:

$$
F(\mathbf{g}) = \sum_{a \in \mathcal{M}} J_a(\mathbf{g}_a) + \sum_{i=1}^N \hat{L}_i(\mathbf{g}_i).
$${#eq-ham-energy}

The update equations are written as a strict gradient descent of @eq-ham-energy:

$$
\tau \dot{\bx}_i = - \nabla_{\mathbf{g}_i} F(\mathbf{g}) = - \left(\sum_{a \in N(i)} \nabla_{\mathbf{g}_i} J_a (\mathbf{g}_a) + \nabla_{\mathbf{g}_i} \hat{\mathcal{L}}_i(\mathbf{g}_i) \right) = - \left(\sum_{a \in N(i)} \nabla_{\mathbf{g}_i} J_a (\mathbf{g}_a) + \bx_i \right),
$${#eq-ham-update}

where $N(i)$ is the set of all factors neighboring at least one variable node in the set $\mathcal{R}_i$. Discretely, this update rule can be written as

$$
\bx_i^{(t+1)} = -\gamma \left(\sum_{a \in N(i)} \nabla_{\mathbf{g}_i} J_a (\mathbf{g}_a^{(t)}) + \bx_i^{(t)} \right) + \bx_i^{(t)}.
$${#eq-ham-discrete-update}

At discrete stepsize $\gamma = 1$, the continuous system in @eq-ham-update loses its decay term and becomes

$$
\bx_i^{(t+1)} = - \sum_{a \in N(i)} \nabla_{\mathbf{g}_i} J_a (\mathbf{g}_a^{(t)}).
$${#eq-ham-discrete-update-gamma-1}

**TODO: The notation clashes below and is not clear. Fix the indices**

Indeed, this update rule looks eerily similar (though not exact) to @eq-belief, written in log-space. First, note that the Legendre Transform has a very nice property relating conjugate variables $(\bx_i, \mathbf{g}_i)$: each is a function of the other. That is, $\mathbf{g}_i = \f{\mathbf{g}_i}(\bx_i)$ can be written as a function of $\bx_i$, and $\bx_i = \f{\bx_i}(\mathbf{g}_i)$ can be written as a function of $\mathbf{g}_i$, where $\f{\bx_i} := \partial_0 \hat{\mathcal{L}}_i$ from @eq-legendre-transform.

Thus, we are tempted to define $\f{\bx_i}^{(t)}(\mathbf{g}_i) := \log b_i^{(t)} (\mathbf{g}_i)$ to be an unnormalized **log-belief**, and define a new kind of **log-message** $\tilde{m}_{a \to i}(\mathbf{g}_a^{(t)}) := - \nabla_{\mathbf{g}_i} J_a (\mathbf{g}_a^{(t)})$ from the update rule in @eq-ham-discrete-update-gamma-1. The handwavy similarity is as follows:


$$
\begin{alignat}{2}
&\text{BP belief computation}
\;\;&&\Longleftrightarrow\;\;
\text{Hopfield memory retrieval}
\\
&b_i^{(t)}(x_i) = \prod_{a \in N(i)} m_{a \to i}^{(t)}(x_i)
\hspace{0.5cm}&&\Longleftrightarrow \hspace{0.5cm}
\f{\bx_i}^{(t+1)}(\mathbf{g}_i) = \sum_{a \in N(i)} \tilde{m}_{a \to i}^{(t)}(\mathbf{g}_a).
\end{alignat}
$$

Though the above does not express equivalence between the log-messages of memory retrieval and the standard messages of BP, it does reveal that both approaches use some form of local signal propagation between the variables.

The case made in these notes is that this formulation of the update rule in HAMs is a fully parallel version of the iterative update of BP. Like BP, HAMs perform inference using message passing, but the passed messages are computed directly as the gradient of the interaction energies which leads to strong convergence guarantees for any factor graph, a guarantee that is missing in conventional loopy BP.

However, we need to understand the variational inference approach to understand the similarities further.

## Hopfield Memory Retrieval from the perspective of Variational Inference

### Background on Variational Inference

Let's begin by describing a *functional of the beliefs* $F_{\text{Bethe}}(b_i, b_a)$. Let's assume a system of $N$ particles, where the state of the $i$-th particle is labeled $x_i$, where for the purpose of these notes we assume $x_i$ is discrete and can take $M_i$ possible values (e.g., $x_i$ is one channel of an RGB pixel and can take 256 possible discrete values). The overall state of the system can then be described by $\bx = \{x_1, x_2, \ldots, x_N \}$, and we denote the set of all possible states as $S$ (e.g., the size of $S$, or the total number of possible states, for CIFAR is $|S| = 256^{3072}$), and each state $\bx \in S$ has a corresponding energy $E(\bx)$. According to the Boltzmann law for given coldness $\beta$ which states

$$
p(\bx) = Z(\beta)^{-1} e^{-\beta E(\bx)}
$${#eq-boltzmann}

using partition function

$$
Z(\beta) = \sum_{\bx \in S} e^{-\beta E(\bx)},
$$

we can write the factor graph representation of $p(\bx) = Z^{-1} \prod_{a=1}^{M} f_a(\bx_a)$ using its energy (defined through the Boltzmann distribution)

$$
E(\bx) = - \left(\sum_{a = 1}^M \ln f_a (\bx_a) \right).
$$

The *Helmholtz Free Energy* of this system is $F_\text{Helmholtz} = -\ln Z(\beta)$, and our goal is to get the best approximation of $F_\text{Helmholtz}$ as possible.

:::{.callout-note}
At this point, @yedidiaProbabilistic began assuming a coldness of $\beta = 1$, which allowed him to not specify $\beta$ in the subsequent equations. For my own understanding it would be important to know which entities are functions of the temperature and which aren't, but until that is clarified for me I will only reproduce his equations.
:::

One important technique is based on the variational approach. Suppose that $p(\bx)$ is the true probability distribution of the system which obeys Boltzmann's law (@eq-boltzmann). Even if we know $p(\bx)$ exactly, it is possible that the computation of $F_\text{Helmholtz}$ is difficult. Therefore, let us introduce a "trial" distribution $b(\bx)$ and a corresponding *variational free energy* (a.k.a. the *Gibbs free energy*)

$$
F(b) = U(b) - H(b),
$$

(note that this energy is defined on the beliefs, not the states themselves) where 

$$
U(b) = \sum_{\bx \in S} b(\bx) E(\bx)
$$

is the *variational average energy*, and 

$$
H(b) = -\sum_{\bx \in S} b(\bx) \ln b(\bx)
$$

is the *variational entropy*. Then, it follows from the definitions that 

$$
F(b) = F_\text{Helmholtz} + D(b || p),
$${#eq-gibbs}

where 

$$
D(b || p) := \sum_{\bx \in S} b(\bx) \ln \frac{b(\bx)}{p(\bx)}
$$

is the KL-Divergence between $b(\bx)$ and $p(\bx)$. Because $D(b || p)$ is non-negative and equal to 0 iff $b(\bx) = p(\bx)$, $F(b) \geq F_\text{Helmholtz}$, with equality precisely when $b(\bx) = p(\bx)$.

**Minimizing $F(b)$ is therefore an exact procedure for computing $F_\text{Helmholtz}$ and recovering $p(\bx)$.** However, as $N$ becomes large, this procedure is intractable because $b(\bx)$ will take exponentially large memory just to store. 

:::{.callout-note}
discuss why $b(\bx)$ requires exponentially large memory just to store?
:::

It is better to minimize $F(b)$ over a restricted class of prob. distributions, which is the idea of mean-field distributions where $b_\text{MF}(\bx) = \prod_{i=1}^N x_i$ defines beliefs that are totally independent of one another.

:::{.callout-note}
The distinction between Gibbs Free Energy and Helmholtz Free Energy is a bit unclear to me. Helmholtz's Free Energy is not a function of anything but the temperature. Meanwhile, Gibbs Free Energy is a function of the beliefs.

I'm also confused by the belief equations of (20) and (21). Do I really sum over all possible states for each belief? That's not at all what associative memory does.
:::


## Background on Variational Inference (from Jordan and Weiss)

- Convert probabilistic inference problem into an optimization problem
- Similar to importance sampling:

  > While Gibbs sampling and Metropolis-Hastings aim at sampling from p(x), **importance sampling** is a Monte Carlo technique in which samples are chosen from a simpler distribution  $q(x)$, and these samples are reweighted appropriately. In particular, we approximate the expectation of a function $f(x)$ as follows:
  > 
  > $E[f(x)] = \sum_x p(x) f(x) = \sum_x q(x) \frac{p(x)}{q(x)} f(x) \approx \frac1N \sum_{i=1}^N \frac{p(x^{(t)})}{q(x^{(t)})} f(x^{(t)})$
  > 
  >  The choice of $q(x)$ is in the hands of the designer, and the idea is that $q(x)$ should be chosen to be relatively simple to sample from, while reasonably close to $p(x)$ so that the weight $p(x(t))/q(x(t))$ is reasonably large. In the  graphical model setting, natural choices of q(x) are often provided by simplifying the graph  underlying p(x) in some way, in particular by deleting edges.

  However, instead of instead of choosing a single $q(x)$ a-priori, a family of approximating distributions $\{(q(x)\)$ is used and the optimization machinery chooses a particular member from this family.

**Note 1**: $p(x)$ can be viewed as the solution to an optimization problem. Define *energy* $E(x) = -\log p(x) - \log Z$, and define the *variational free energy* as

$$
\begin{aligned}
F(\{q(x)\}) &= \sum_x q(x) E(x) + \sum_x q(x) \log q(x) \\
&= - \sum_x q(x) \log p(x) + \sum_x q(x) \log q(x) - \log Z
\end{aligned}
$$

(which is equal to the KL divergence between $q(x)$ and $p(x)$, and is minimized when $q(x) = p(x)$, attaining value of $-\log Z$ at the minimum)


The variational approach must be converted 